BEGIN
   FOR c IN (SELECT table_name FROM user_tables WHERE table_name IN ('FATO_VENDAS', 'DIM_CLIENTE', 'DIM_PRODUTO', 'DIM_TEMPO', 'DIM_VENDEDOR', 'DIM_LOCALIDADE')) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
   FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_DIM_%') LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
   END LOOP;
END;
/

-- Tabela de Dimensão de Tempo
CREATE TABLE DIM_TEMPO (
    SK_TEMPO          NUMBER(10) PRIMARY KEY,
    DATA_COMPLETA     DATE NOT NULL,
    DIA               NUMBER(2) NOT NULL,
    MES               NUMBER(2) NOT NULL,
    ANO               NUMBER(4) NOT NULL,
    NOME_MES          VARCHAR2(20) NOT NULL,
    TRIMESTRE         CHAR(2) NOT NULL,
    SEMESTRE          CHAR(2) NOT NULL
);
CREATE SEQUENCE SEQ_DIM_TEMPO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Dimensão de Cliente
CREATE TABLE DIM_CLIENTE (
    SK_CLIENTE          NUMBER(10) PRIMARY KEY,
    COD_CLIENTE_ORIGEM  NUMBER(10) NOT NULL, 
    NOME_CLIENTE        VARCHAR2(50) NOT NULL,
    TIPO_PESSOA         CHAR(1),
    CPF_CNPJ            VARCHAR2(20)
);
CREATE SEQUENCE SEQ_DIM_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Dimensão de Vendedor
CREATE TABLE DIM_VENDEDOR (
    SK_VENDEDOR         NUMBER(10) PRIMARY KEY,
    COD_VENDEDOR_ORIGEM NUMBER(4) NOT NULL, 
    NOME_VENDEDOR       VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE SEQ_DIM_VENDEDOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Dimensão de Produto
CREATE TABLE DIM_PRODUTO (
    SK_PRODUTO          NUMBER(10) PRIMARY KEY,
    COD_PRODUTO_ORIGEM  NUMBER(10) NOT NULL, 
    NOME_PRODUTO        VARCHAR2(50) NOT NULL,
    COD_BARRA           VARCHAR2(20)
);
CREATE SEQUENCE SEQ_DIM_PRODUTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela de Dimensão de Localidade
CREATE TABLE DIM_LOCALIDADE (
    SK_LOCALIDADE       NUMBER(10) PRIMARY KEY,
    COD_CIDADE_ORIGEM   NUMBER(6),
    CIDADE              VARCHAR2(30),
    ESTADO              VARCHAR2(50),
    PAIS                VARCHAR2(50)
);
CREATE SEQUENCE SEQ_DIM_LOCALIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tabela Fato de Vendas
CREATE TABLE FATO_VENDAS (
    SK_CLIENTE          NUMBER(10) REFERENCES DIM_CLIENTE(SK_CLIENTE),
    SK_VENDEDOR         NUMBER(10) REFERENCES DIM_VENDEDOR(SK_VENDEDOR),
    SK_PRODUTO          NUMBER(10) REFERENCES DIM_PRODUTO(SK_PRODUTO),
    SK_TEMPO            NUMBER(10) REFERENCES DIM_TEMPO(SK_TEMPO),
    SK_LOCALIDADE       NUMBER(10) REFERENCES DIM_LOCALIDADE(SK_LOCALIDADE),
    COD_PEDIDO          NUMBER(10),
    QUANTIDADE_VENDIDA  NUMBER(10),
    VALOR_UNITARIO      NUMBER(12,2),
    VALOR_DESCONTO      NUMBER(12,2),
    VALOR_TOTAL_ITEM    NUMBER(12,2),
    CONSTRAINT PK_FATO_VENDAS PRIMARY KEY (SK_CLIENTE, SK_VENDEDOR, SK_PRODUTO, SK_TEMPO, SK_LOCALIDADE, COD_PEDIDO)
);

