DROP TABLE FATO_VENDAS CASCADE CONSTRAINTS;
DROP TABLE DIM_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE DIM_VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE DIM_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE DIM_TEMPO CASCADE CONSTRAINTS;
DROP TABLE DIM_LOCALIDADE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DIM_CLIENTE;
DROP SEQUENCE SEQ_DIM_VENDEDOR;
DROP SEQUENCE SEQ_DIM_PRODUTO;
DROP SEQUENCE SEQ_DIM_TEMPO;
DROP SEQUENCE SEQ_DIM_LOCALIDADE;
-- DIMENSÕES

CREATE TABLE DIM_CLIENTE (
    SK_CLIENTE NUMBER PRIMARY KEY,
    COD_CLIENTE_ORIGEM NUMBER,
    NOME_CLIENTE VARCHAR2(50),
    TIPO_PESSOA CHAR(1),
    CPF_CNPJ VARCHAR2(20)
);

CREATE SEQUENCE SEQ_DIM_CLIENTE START WITH 1 INCREMENT BY 1;

CREATE TABLE DIM_VENDEDOR (
    SK_VENDEDOR NUMBER PRIMARY KEY,
    COD_VENDEDOR_ORIGEM NUMBER,
    NOME_VENDEDOR VARCHAR2(50)
);

CREATE SEQUENCE SEQ_DIM_VENDEDOR START WITH 1 INCREMENT BY 1;

CREATE TABLE DIM_PRODUTO (
    SK_PRODUTO NUMBER PRIMARY KEY,
    COD_PRODUTO_ORIGEM NUMBER,
    NOME_PRODUTO VARCHAR2(50),
    COD_BARRA VARCHAR2(20)
);

CREATE SEQUENCE SEQ_DIM_PRODUTO START WITH 1 INCREMENT BY 1;

CREATE TABLE DIM_TEMPO (
    SK_TEMPO NUMBER PRIMARY KEY,
    DATA_COMPLETA DATE,
    DIA NUMBER,
    MES NUMBER,
    ANO NUMBER,
    NOME_MES VARCHAR2(20),
    TRIMESTRE CHAR(2),
    SEMESTRE CHAR(2)
);

CREATE SEQUENCE SEQ_DIM_TEMPO START WITH 1 INCREMENT BY 1;

CREATE TABLE DIM_LOCALIDADE (
    SK_LOCALIDADE NUMBER PRIMARY KEY,
    COD_CIDADE_ORIGEM NUMBER,
    CIDADE VARCHAR2(30),
    ESTADO VARCHAR2(50),
    PAIS VARCHAR2(50)
);

CREATE SEQUENCE SEQ_DIM_LOCALIDADE START WITH 1 INCREMENT BY 1;

-- TABELA FATO

CREATE TABLE FATO_VENDAS (
    SK_CLIENTE NUMBER,
    SK_VENDEDOR NUMBER,
    SK_PRODUTO NUMBER,
    SK_TEMPO NUMBER,
    SK_LOCALIDADE NUMBER,
    COD_PEDIDO NUMBER,
    QUANTIDADE_VENDIDA NUMBER,
    VALOR_UNITARIO NUMBER(12,2),
    VALOR_DESCONTO NUMBER(12,2),
    VALOR_TOTAL_ITEM NUMBER(12,2),
    CONSTRAINT PK_FATO_VENDAS PRIMARY KEY (SK_CLIENTE, SK_VENDEDOR, SK_PRODUTO, SK_TEMPO, COD_PEDIDO)
);

