CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_CLIENTE
AFTER INSERT ON DIM_CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_CLIENTE', 'INSERT', SYSDATE, USER);
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/