CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_CLIENTE
AFTER INSERT ON DIM_CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_CLIENTE', 'INSERT', SYSDATE, USER);
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

SET SERVEROUTPUT ON;

BEGIN
    PKG_ETL_VENDAS.PRC_CARGA_GERAL_ETL;
END;
/

SELECT COUNT(*) AS TOTAL_REGISTROS_NA_FATO FROM FATO_VENDAS;
