
CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_CLIENTE
AFTER INSERT ON DIM_CLIENTE
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_CLIENTE', 'INSERT', SYSDATE, USER);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_VENDEDOR
AFTER INSERT ON DIM_VENDEDOR
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_VENDEDOR', 'INSERT', SYSDATE, USER);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_PRODUTO
AFTER INSERT ON DIM_PRODUTO
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_PRODUTO', 'INSERT', SYSDATE, USER);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_LOCAL
AFTER INSERT ON DIM_LOCALIDADE
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_LOCALIDADE', 'INSERT', SYSDATE, USER);
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITA_INSERT_DIM_TEMPO
AFTER INSERT ON DIM_TEMPO
BEGIN
    INSERT INTO TB_AUDITORIA (TABELA, OPERACAO, DATA, USUARIO)
    VALUES ('DIM_TEMPO', 'INSERT', SYSDATE, USER);
END;
/
