-- Tabela de auditoria
DROP TABLE AUDITORIA_DW CASCADE CONSTRAINTS;

CREATE TABLE AUDITORIA_DW (
    ID_AUDIT NUMBER GENERATED ALWAYS AS IDENTITY,
    TABELA VARCHAR2(50),
    OPERACAO VARCHAR2(10),
    USUARIO_BD VARCHAR2(30),
    DATA_REGISTRO DATE DEFAULT SYSDATE
);

-- Trigger para DIM_CLIENTE
CREATE OR REPLACE TRIGGER TRG_AUDIT_DIM_CLIENTE
AFTER INSERT ON DIM_CLIENTE
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DW (TABELA, OPERACAO, USUARIO_BD)
    VALUES ('DIM_CLIENTE','INSERT',USER);
END;
/

-- Trigger para DIM_VENDEDOR
CREATE OR REPLACE TRIGGER TRG_AUDIT_DIM_VENDEDOR
AFTER INSERT ON DIM_VENDEDOR
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_DW (TABELA, OPERACAO, USUARIO_BD)
    VALUES ('DIM_VENDEDOR','INSERT',USER);
END;
/
