SET SERVEROUTPUT ON;

BEGIN
    PKG_ETL_VENDAS.PRC_CARGA_GERAL_ETL;
END;
/

SELECT COUNT(*) AS TOTAL_REGISTROS_NA_FATO FROM FATO_VENDAS;

SELECT SK_LOCALIDADE, COUNT(*) AS QTD_REGISTROS
FROM FATO_VENDAS
GROUP BY SK_LOCALIDADE
ORDER BY SK_LOCALIDADE;