SELECT
    A.NOME_PAIS AS PAIS,
    COUNT(DISTINCT B.NOME_ESTADO) AS "QTD ESTADOS"
FROM 
    PAIS A 
    LEFT JOIN ESTADO B ON A.ID_PAIS = B.ID_PAIS
GROUP BY 
    A.NOME_PAIS
    --BUSCA DE ESTADOS QUE CONTENHAM MAIS DE 5 ESTADOS == HAVING COUNT(DISTINCT B.NOME_ESTADO) >5
    --ORDER BY 2
    ;
